import './globals.css';
import type { Metadata } from 'next';
// import { cookies } from 'next/headers';
import { Inter } from 'next/font/google';

import { Copyright } from '@/components/copyright/copyright';
import { Toaster } from '@/components/ui/toaster';
import { cn } from '@/lib/utils';
import { ThemeProvider } from '@/theme/theme-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Image AI',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(inter.className, 'h-full')}>
        <ThemeProvider
          enableSystem
          disableTransitionOnChange
          attribute="class"
          defaultTheme="dark"
        >
          {children}
          <Copyright />
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
