import './globals.css';
import type { Metadata } from 'next';
// import { cookies } from 'next/headers';
import { Inter } from 'next/font/google';
import { ThemeProvider } from '@/theme/theme-provider';
import { cn } from '@/lib/utils';
import { StoreProvider } from '@/store/StoreProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Image AI',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const cookieStore = cookies();
  // console.log('*** cookieStore ***', cookieStore);

  return (
    <html
      lang='en'
      suppressHydrationWarning
    >
      <body className={cn(inter.className, 'h-full')}>
        <StoreProvider>
          <ThemeProvider
            enableSystem
            disableTransitionOnChange
            attribute='class'
            defaultTheme='system'
          >
            {children}
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
